MERGE INTO val.OTC_CNTR_UNAS_PRTC tgt
USING (
    SELECT 
        ?CNTR_ID AS CNTR_ID, 
        ?CNTR_HSTR_NO AS CNTR_HSTR_NO, 
        ?SEQ AS SEQ,
  		?UNAS_ID AS UNAS_ID,
  		?LEG_NO AS LEG_NO,
  		'HS' AS WRKR_ID, 
        '0.0.0.0' AS WORK_TRIP 
    FROM DUAL
) src
ON (tgt.CNTR_ID = src.CNTR_ID AND tgt.CNTR_HSTR_NO = src.CNTR_HSTR_NO)
WHEN MATCHED THEN
    UPDATE SET tgt.WORK_TIME = SYSDATE
WHEN NOT MATCHED THEN
    INSERT (CNTR_ID, CNTR_HSTR_NO, SEQ, UNAS_ID, LEG_NO, WRKR_ID, WORK_TRIP, WORK_TIME) 
    VALUES (src.CNTR_ID, src.CNTR_HSTR_NO, src.SEQ, src.UNAS_ID, src.LEG_NO, src.WRKR_ID, src.WORK_TRIP, SYSDATE)