MERGE INTO val.OTC_EXEC_SCHD_PRTC tgt
USING (
    SELECT 
        ?GDS_ID AS GDS_ID, 
        ?CNTR_HSTR_NO AS CNTR_HSTR_NO, 
        ?LEG_NO AS LEG_NO,
  		?EXEC_TP AS EXEC_TP,
  		?EXEC_GDS_NO AS EXEC_GDS_NO,
  		?SQNC AS SQNC,
  		?EVLT_DT AS EVLT_DT,
  		?ACTP_RT AS ACTP_RT,
  		?CPN_RT AS CPN_RT,
  		?SETL_DT AS SETL_DT,
        'HS' AS WRKR_ID, 
        '0.0.0.0' AS WORK_TRIP 
    FROM DUAL
) src
ON (tgt.GDS_ID = src.GDS_ID AND tgt.CNTR_HSTR_NO = src.CNTR_HSTR_NO AND tgt.LEG_NO = src.LEG_NO AND tgt.SQNC = src.SQNC)
WHEN MATCHED THEN
    UPDATE SET tgt.WORK_TIME = SYSDATE
WHEN NOT MATCHED THEN
    INSERT (GDS_ID, CNTR_HSTR_NO, LEG_NO, EXEC_TP, EXEC_GDS_NO, SQNC, EVLT_DT, ACTP_RT, CPN_RT, SETL_DT, WRKR_ID, WORK_TRIP, WORK_TIME) 
    VALUES (src.GDS_ID, src.CNTR_HSTR_NO, src.LEG_NO, src.EXEC_TP, src.EXEC_GDS_NO, src.SQNC, src.EVLT_DT, src.ACTP_RT, src.CPN_RT, src.SETL_DT, src.WRKR_ID, src.WORK_TRIP, SYSDATE)