MERGE INTO val.otc_crlt_cfcn_data_prtc tgt
USING (
    SELECT 
        ?BASE_DT AS BASE_DT, 
        ?DATA_SET_ID AS DATA_SET_ID, 
        ?DATA_ID AS DATA_ID,
  		?CRLT_CFCN_MATX_ID AS CRLT_CFCN_MATX_ID,
        ?TH01_DATA_ID AS TH01_DATA_ID,
  		?TH02_DATA_ID AS TH02_DATA_ID,
  		?CRLT_CFCN AS CRLT_CFCN,
  		?BASE_DT AS OCR_DT,
        'MANUALLY_INPUT' AS PGM_ID, 
        'HS' AS WRKR_ID, 
        '0.0.0.0' AS WORK_TRIP 
        
    FROM DUAL
) src
ON (tgt.BASE_DT = src.BASE_DT AND tgt.DATA_SET_ID = src.DATA_SET_ID AND tgt.DATA_ID = src.DATA_ID)
WHEN MATCHED THEN
    UPDATE SET tgt.CRLT_CFCN = src.CRLT_CFCN, tgt.WORK_TIME = SYSDATE
WHEN NOT MATCHED THEN
    INSERT (BASE_DT, DATA_SET_ID, DATA_ID, CRLT_CFCN_MATX_ID, TH01_DATA_ID, TH02_DATA_ID, CRLT_CFCN, OCR_DT, PGM_ID, WRKR_ID, WORK_TRIP, WORK_TIME) 
    VALUES (src.BASE_DT, src.DATA_SET_ID, src.DATA_ID, src.CRLT_CFCN_MATX_ID, src.TH01_DATA_ID, src.TH02_DATA_ID, src.CRLT_CFCN, src.OCR_DT, src.PGM_ID, src.WRKR_ID, src.WORK_TRIP, SYSDATE)