MERGE INTO val.OTC_VLTL_CURV_DATA_PRTC tgt
USING (
    SELECT 
        ?BASE_DT AS BASE_DT, 
        ?DATA_SET_ID AS DATA_SET_ID, 
        ?DATA_ID AS DATA_ID,
  		1 AS EXPR_VAL,
        ?VLTL_RT AS VLTL_RT,
  		?DATA_ID AS RISK_FCTR_CODE,
  		?BASE_DT AS OCR_DT,
        'MANUALLY_INPUT' AS PGM_ID, 
        'HS' AS WRKR_ID, 
        '0.0.0.0' AS WORK_TRIP 
    FROM DUAL
) src
ON (tgt.BASE_DT = src.BASE_DT AND tgt.DATA_SET_ID = src.DATA_SET_ID AND tgt.DATA_ID = src.DATA_ID)
WHEN MATCHED THEN
    UPDATE SET tgt.VLTL_RT = src.VLTL_RT, tgt.WORK_TIME = SYSDATE
WHEN NOT MATCHED THEN
    INSERT (BASE_DT, DATA_SET_ID, DATA_ID, EXPR_VAL, VLTL_RT, RISK_FCTR_CODE, OCR_DT, PGM_ID, WRKR_ID, WORK_TRIP, WORK_TIME) 
    VALUES (src.BASE_DT, src.DATA_SET_ID, src.DATA_ID, src.EXPR_VAL, src.VLTL_RT, src.RISK_FCTR_CODE, src.OCR_DT, src.PGM_ID, src.WRKR_ID, src.WORK_TRIP, SYSDATE)