INSERT INTO val.OTC_EXEC_SCHD_PRTC 
	(GDS_ID, CNTR_HSTR_NO, LEG_NO, EXEC_TP, EXEC_GDS_NO, SQNC, EVLT_DT, ACTP_RT, CPN_RT, SETL_DT, WORK_TIME) 
VALUES 
	(?GDS_ID, 1, 0, 'A', '1', ?SQNC, ?EVLT_DT, ?ACTP_RT, ?CPN_RT, ?SETL_DT, SYSDATE)