MERGE INTO val.OTC_BRR_MSTR tgt
USING (
    SELECT 
        ?GDS_ID AS GDS_ID, 
        ?CNTR_HSTR_NO AS CNTR_HSTR_NO, 
        ?LEG_NO AS LEG_NO, 
        ?BRR_TP AS BRR_TP,
  		?BRR_GDS_NO AS BRR_GDS_NO,
  		?SRC_COND_TP AS SRC_COND_TP,
  		?COND_RANGE_TP AS COND_RANGE_TP,
  		?OBRA_PRIC_TYPE_TP AS OBRA_PRIC_TYPE_TP,
        'HS' AS WRKR_ID, 
        '0.0.0.0' AS WORK_TRIP 
    FROM DUAL
) src
ON (tgt.GDS_ID = src.GDS_ID AND tgt.CNTR_HSTR_NO = src.CNTR_HSTR_NO AND tgt.LEG_NO = src.LEG_NO)
WHEN MATCHED THEN
    UPDATE SET tgt.WORK_TIME = SYSDATE
WHEN NOT MATCHED THEN
    INSERT (GDS_ID, CNTR_HSTR_NO, LEG_NO, BRR_TP, BRR_GDS_NO, SRC_COND_TP, COND_RANGE_TP, OBRA_PRIC_TYPE_TP, WRKR_ID, WORK_TRIP, WORK_TIME) 
    VALUES (src.GDS_ID, src.CNTR_HSTR_NO, src.LEG_NO, src.BRR_TP, src.BRR_GDS_NO, src.SRC_COND_TP, src.COND_RANGE_TP, src.OBRA_PRIC_TYPE_TP, src.WRKR_ID, src.WORK_TRIP, SYSDATE)