MERGE INTO val.OTC_CNTR_MSTR tgt
USING (
    SELECT 
        ?CNTR_ID AS CNTR_ID, 
        ?CNTR_HSTR_NO AS CNTR_HSTR_NO, 
        ?ISIN_CODE AS ISIN_CODE,
  		?CNTR_CODE AS CNTR_CODE,
  		?CNTR_TYPE_TP AS CNTR_TYPE_TP,
  		?GDS_TMPL_TP AS GDS_TMPL_TP,
  		?DEAL_DT AS DEAL_DT,
  		?AVLB_DT AS AVLB_DT,
  		?END_DT AS END_DT,
  		?BUY_SELL_TP AS BUY_SELL_TP,
  		?NMNL_AMT AS NMNL_AMT,
  		?NMNL_AMT_CRNC_CODE AS NMNL_AMT_CRNC_CODE,
  		?FV_LEVL_TP AS FV_LEVL_TP,
  		?INSD_OTSD_EVLT_TP AS INSD_OTSD_EVLT_TP,
  		?BASEP_DTRM_DT AS BASEP_DTRM_DT,
        'HS' AS WRKR_ID, 
        '0.0.0.0' AS WORK_TRIP 
    FROM DUAL
) src
ON (tgt.CNTR_ID = src.CNTR_ID AND tgt.CNTR_HSTR_NO = src.CNTR_HSTR_NO)
WHEN MATCHED THEN
    UPDATE SET tgt.WORK_TIME = SYSDATE
WHEN NOT MATCHED THEN
    INSERT (CNTR_ID, CNTR_HSTR_NO, ISIN_CODE, CNTR_CODE, CNTR_TYPE_TP, GDS_TMPL_TP, DEAL_DT, AVLB_DT, END_DT, BUY_SELL_TP, NMNL_AMT, NMNL_AMT_CRNC_CODE, FV_LEVL_TP, INSD_OTSD_EVLT_TP, BASEP_DTRM_DT, WRKR_ID, WORK_TRIP, WORK_TIME) 
    VALUES (src.CNTR_ID, src.CNTR_HSTR_NO, src.ISIN_CODE, src.CNTR_CODE, src.CNTR_TYPE_TP, src.GDS_TMPL_TP, src.DEAL_DT, src.AVLB_DT, src.END_DT, src.BUY_SELL_TP, src.NMNL_AMT, src.NMNL_AMT_CRNC_CODE, src.FV_LEVL_TP, src.INSD_OTSD_EVLT_TP, src.BASEP_DTRM_DT, src.WRKR_ID, src.WORK_TRIP, SYSDATE)