MERGE INTO val.OTC_ERRT_CURV_MSTR tgt
USING (
    SELECT 
        ?DATA_ID AS DATA_ID, 
        ?DATA_NM AS DATA_NM, 
        'FWDC' AS ERRT_CURV_TP, 
        ?CRNC_CODE AS CRNC_CODE,
  		?RELT_CRNC_CODE AS RELT_CRNC_CODE,
  		1 AS CRNC_UNIT_AMT,
  		'MANUALLY_INPUT' AS PGM_ID,
  		'SYSTEM' AS WRKR_ID,
        '0.0.0.0' AS WORK_TRIP 
    FROM DUAL
) src
ON (tgt.DATA_ID = src.DATA_ID)
WHEN MATCHED THEN
    UPDATE SET 
        tgt.DATA_NM = src.DATA_NM,
        tgt.ERRT_CURV_TP = src.ERRT_CURV_TP,
        tgt.CRNC_CODE = src.CRNC_CODE,
        tgt.RELT_CRNC_CODE = src.RELT_CRNC_CODE,
        tgt.CRNC_UNIT_AMT = src.CRNC_UNIT_AMT,
        tgt.PGM_ID = src.PGM_ID,
        tgt.WRKR_ID = src.WRKR_ID,
        tgt.WORK_TRIP = src.WORK_TRIP
WHEN NOT MATCHED THEN
    INSERT (DATA_ID, DATA_NM, ERRT_CURV_TP, CRNC_CODE, RELT_CRNC_CODE, CRNC_UNIT_AMT, PGM_ID, WRKR_ID, WORK_TRIP, WORK_TIME) 
    VALUES (src.DATA_ID, src.DATA_NM, src.ERRT_CURV_TP, src.CRNC_CODE, src.RELT_CRNC_CODE, src.CRNC_UNIT_AMT, src.PGM_ID, src.WRKR_ID, src.WORK_TRIP, SYSDATE)