MERGE INTO val.OTC_PRIC_DATA_PRTC tgt
USING (
    SELECT 
        ?BASE_DT AS BASE_DT, 
        ?DATA_SET_ID AS DATA_SET_ID, 
        ?DATA_ID AS DATA_ID, 
        ?CLOSE_PRIC AS CLOSE_PRIC, 
        ?PGM_ID AS PGM_ID, 
        ?WRKR_ID AS WRKR_ID, 
        ?WORK_TRIP AS WORK_TRIP, 
        TO_TIMESTAMP(?WORK_TIME, 'YYYY-MM-DD HH24:MI:SS') AS WORK_TIME 
    FROM DUAL
) src
ON (tgt.BASE_DT = src.BASE_DT AND tgt.DATA_SET_ID = src.DATA_SET_ID AND tgt.DATA_ID = src.DATA_ID)
WHEN MATCHED THEN
    UPDATE SET tgt.CLOSE_PRIC = src.CLOSE_PRIC, tgt.WORK_TIME = src.WORK_TIME
WHEN NOT MATCHED THEN
    INSERT (BASE_DT, DATA_SET_ID, DATA_ID, CLOSE_PRIC, PGM_ID, WRKR_ID, WORK_TRIP, WORK_TIME) 
    VALUES (src.BASE_DT, src.DATA_SET_ID, src.DATA_ID, src.CLOSE_PRIC, src.PGM_ID, src.WRKR_ID, src.WORK_TRIP, src.WORK_TIME)